print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("Rituraj")
print("Rituraj")
print("Rituraj")
print("Rituraj")
print("Rituraj1")
print("Rituraj1")
print("Rituraj1")
print("Rituraj1")
print("Rituraj")
print("Rituraj")
print("Rituraj")
print("Rituraj")
print("Rituraj1")
print("Rituraj1")
print("Rituraj1")
print("Rituraj1")
